// Mock data for the Smart Agri Connect application

export const crops = [
  {
    id: '1',
    name: 'Organic Tomatoes',
    farmer: 'Rajesh Kumar',
    farmerId: 'f1',
    price: 45,
    unit: 'kg',
    quantity: 500,
    quality: 'Premium',
    location: 'Nashik, Maharashtra',
    distance: 25,
    rating: 4.8,
    image: '/crops/tomatoes.jpg',
    category: 'Vegetables',
    harvestDate: '2026-03-28',
    isBestDeal: true,
  },
  {
    id: '2',
    name: 'Basmati Rice',
    farmer: 'Suresh Patel',
    farmerId: 'f2',
    price: 85,
    unit: 'kg',
    quantity: 2000,
    quality: 'Grade A',
    location: 'Punjab',
    distance: 150,
    rating: 4.9,
    image: '/crops/rice.jpg',
    category: 'Grains',
    harvestDate: '2026-03-20',
    isBestDeal: false,
  },
  {
    id: '3',
    name: 'Fresh Onions',
    farmer: 'Mahesh Deshmukh',
    farmerId: 'f3',
    price: 30,
    unit: 'kg',
    quantity: 800,
    quality: 'Standard',
    location: 'Lasalgaon, Maharashtra',
    distance: 45,
    rating: 4.5,
    image: '/crops/onions.jpg',
    category: 'Vegetables',
    harvestDate: '2026-03-25',
    isBestDeal: true,
  },
  {
    id: '4',
    name: 'Yellow Lentils',
    farmer: 'Amit Singh',
    farmerId: 'f4',
    price: 120,
    unit: 'kg',
    quantity: 600,
    quality: 'Premium',
    location: 'Indore, MP',
    distance: 200,
    rating: 4.7,
    image: '/crops/lentils.jpg',
    category: 'Pulses',
    harvestDate: '2026-03-15',
    isBestDeal: false,
  },
  {
    id: '5',
    name: 'Green Chilies',
    farmer: 'Prakash Reddy',
    farmerId: 'f5',
    price: 60,
    unit: 'kg',
    quantity: 300,
    quality: 'Grade A',
    location: 'Guntur, AP',
    distance: 400,
    rating: 4.6,
    image: '/crops/chilies.jpg',
    category: 'Vegetables',
    harvestDate: '2026-03-30',
    isBestDeal: false,
  },
  {
    id: '6',
    name: 'Organic Wheat',
    farmer: 'Vijay Sharma',
    farmerId: 'f6',
    price: 32,
    unit: 'kg',
    quantity: 5000,
    quality: 'Premium',
    location: 'Haryana',
    distance: 180,
    rating: 4.9,
    image: '/crops/wheat.jpg',
    category: 'Grains',
    harvestDate: '2026-03-22',
    isBestDeal: true,
  },
]

export const farmers = [
  {
    id: 'f1',
    name: 'Rajesh Kumar',
    location: 'Nashik, Maharashtra',
    rating: 4.8,
    totalSales: 245000,
    crops: ['Tomatoes', 'Onions', 'Potatoes'],
    verified: true,
    avatar: undefined,
    phone: '+91 98765 43210',
    joinedDate: '2024-01-15',
    preferredStatus: true,
  },
  {
    id: 'f2',
    name: 'Suresh Patel',
    location: 'Punjab',
    rating: 4.9,
    totalSales: 890000,
    crops: ['Rice', 'Wheat'],
    verified: true,
    avatar: undefined,
    phone: '+91 98765 43211',
    joinedDate: '2023-06-20',
    preferredStatus: true,
  },
  {
    id: 'f3',
    name: 'Mahesh Deshmukh',
    location: 'Lasalgaon, Maharashtra',
    rating: 4.5,
    totalSales: 156000,
    crops: ['Onions', 'Garlic'],
    verified: true,
    avatar: undefined,
    phone: '+91 98765 43212',
    joinedDate: '2024-03-10',
    preferredStatus: false,
  },
  {
    id: 'f4',
    name: 'Amit Singh',
    location: 'Indore, MP',
    rating: 4.7,
    totalSales: 320000,
    crops: ['Lentils', 'Chickpeas', 'Soybeans'],
    verified: true,
    avatar: undefined,
    phone: '+91 98765 43213',
    joinedDate: '2023-09-05',
    preferredStatus: true,
  },
  {
    id: 'f5',
    name: 'Prakash Reddy',
    location: 'Guntur, AP',
    rating: 4.6,
    totalSales: 445000,
    crops: ['Chilies', 'Turmeric', 'Cotton'],
    verified: true,
    avatar: undefined,
    phone: '+91 98765 43214',
    joinedDate: '2023-11-18',
    preferredStatus: false,
  },
]

export const orders = [
  {
    id: 'ORD-001',
    crop: 'Organic Tomatoes',
    farmer: 'Rajesh Kumar',
    quantity: 100,
    unit: 'kg',
    totalPrice: 4500,
    status: 'completed',
    orderDate: '2026-03-25',
    deliveryDate: '2026-03-28',
  },
  {
    id: 'ORD-002',
    crop: 'Basmati Rice',
    farmer: 'Suresh Patel',
    quantity: 500,
    unit: 'kg',
    totalPrice: 42500,
    status: 'pending',
    orderDate: '2026-04-01',
    deliveryDate: '2026-04-05',
  },
  {
    id: 'ORD-003',
    crop: 'Fresh Onions',
    farmer: 'Mahesh Deshmukh',
    quantity: 200,
    unit: 'kg',
    totalPrice: 6000,
    status: 'processing',
    orderDate: '2026-03-30',
    deliveryDate: '2026-04-02',
  },
  {
    id: 'ORD-004',
    crop: 'Yellow Lentils',
    farmer: 'Amit Singh',
    quantity: 150,
    unit: 'kg',
    totalPrice: 18000,
    status: 'cancelled',
    orderDate: '2026-03-20',
    deliveryDate: null,
  },
  {
    id: 'ORD-005',
    crop: 'Organic Wheat',
    farmer: 'Vijay Sharma',
    quantity: 1000,
    unit: 'kg',
    totalPrice: 32000,
    status: 'completed',
    orderDate: '2026-03-22',
    deliveryDate: '2026-03-26',
  },
]

export const priceHistory = [
  { month: 'Oct', tomatoes: 42, rice: 80, wheat: 30, onions: 25 },
  { month: 'Nov', tomatoes: 38, rice: 82, wheat: 31, onions: 28 },
  { month: 'Dec', tomatoes: 35, rice: 85, wheat: 32, onions: 35 },
  { month: 'Jan', tomatoes: 40, rice: 83, wheat: 33, onions: 40 },
  { month: 'Feb', tomatoes: 48, rice: 84, wheat: 32, onions: 32 },
  { month: 'Mar', tomatoes: 45, rice: 85, wheat: 32, onions: 30 },
]

export const demandData = [
  { month: 'Oct', demand: 12000, supply: 10000 },
  { month: 'Nov', demand: 15000, supply: 13000 },
  { month: 'Dec', demand: 18000, supply: 14000 },
  { month: 'Jan', demand: 16000, supply: 15000 },
  { month: 'Feb', demand: 20000, supply: 17000 },
  { month: 'Mar', demand: 22000, supply: 19000 },
]

export const cropCategories = [
  { name: 'Vegetables', value: 35, color: 'var(--chart-1)' },
  { name: 'Grains', value: 30, color: 'var(--chart-2)' },
  { name: 'Pulses', value: 15, color: 'var(--chart-3)' },
  { name: 'Fruits', value: 12, color: 'var(--chart-4)' },
  { name: 'Others', value: 8, color: 'var(--chart-5)' },
]

export const topCrops = [
  { name: 'Tomatoes', sales: 45000 },
  { name: 'Rice', sales: 89000 },
  { name: 'Wheat', sales: 67000 },
  { name: 'Onions', sales: 34000 },
  { name: 'Lentils', sales: 28000 },
]

export const regionData = [
  { region: 'Maharashtra', production: 450000, farmers: 12500, avgPrice: 42 },
  { region: 'Punjab', production: 680000, farmers: 18000, avgPrice: 38 },
  { region: 'Haryana', production: 320000, farmers: 9500, avgPrice: 35 },
  { region: 'UP', production: 520000, farmers: 22000, avgPrice: 40 },
  { region: 'MP', production: 280000, farmers: 8500, avgPrice: 36 },
  { region: 'AP', production: 380000, farmers: 11000, avgPrice: 44 },
]

export const governmentStats = {
  totalFarmers: 125000,
  totalSellers: 8500,
  totalTransactions: 892000,
  totalVolume: 4500000,
  pendingApprovals: 156,
  flaggedAccounts: 23,
}

export const procurementData = [
  { crop: 'Rice', target: 100000, procured: 78000, unit: 'tonnes' },
  { crop: 'Wheat', target: 150000, procured: 125000, unit: 'tonnes' },
  { crop: 'Pulses', target: 50000, procured: 32000, unit: 'tonnes' },
  { crop: 'Cotton', target: 80000, procured: 55000, unit: 'bales' },
]

export const mapLocations = [
  { id: 1, name: 'Nashik Farm Cluster', lat: 19.9975, lng: 73.7898, type: 'farm', crops: ['Tomatoes', 'Onions'], production: 25000 },
  { id: 2, name: 'Punjab Grain Hub', lat: 31.1471, lng: 75.3412, type: 'market', crops: ['Rice', 'Wheat'], production: 85000 },
  { id: 3, name: 'Lasalgaon Onion Market', lat: 20.1500, lng: 74.2333, type: 'market', crops: ['Onions'], production: 45000 },
  { id: 4, name: 'Indore Pulse Center', lat: 22.7196, lng: 75.8577, type: 'warehouse', crops: ['Lentils', 'Chickpeas'], production: 32000 },
  { id: 5, name: 'Guntur Spice Zone', lat: 16.3067, lng: 80.4365, type: 'farm', crops: ['Chilies', 'Turmeric'], production: 28000 },
]

export const reviews = [
  {
    id: '1',
    farmerId: 'f1',
    farmerName: 'Rajesh Kumar',
    rating: 5,
    comment: 'Excellent quality tomatoes, delivered on time!',
    date: '2026-03-28',
    cropPurchased: 'Organic Tomatoes',
  },
  {
    id: '2',
    farmerId: 'f2',
    farmerName: 'Suresh Patel',
    rating: 5,
    comment: 'Best rice quality in the region. Highly recommended!',
    date: '2026-03-25',
    cropPurchased: 'Basmati Rice',
  },
  {
    id: '3',
    farmerId: 'f3',
    farmerName: 'Mahesh Deshmukh',
    rating: 4,
    comment: 'Good quality onions, minor delay in delivery.',
    date: '2026-03-22',
    cropPurchased: 'Fresh Onions',
  },
]
