"use client"

import {
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts"

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"

const monthlySales = [
  { month: "Jan", sales: 12000 },
  { month: "Feb", sales: 18000 },
  { month: "Mar", sales: 15000 },
  { month: "Apr", sales: 22000 },
  { month: "May", sales: 26000 },
  { month: "Jun", sales: 21000 },
]

const cropData = [
  { name: "Rice", value: 400 },
  { name: "Wheat", value: 300 },
  { name: "Tomatoes", value: 200 },
  { name: "Onions", value: 150 },
]

const COLORS = ["#22c55e", "#3b82f6", "#f59e0b", "#ef4444"]

export default function FarmerAnalyticsPage() {
  return (
    <div className="space-y-6">

      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold">Analytics</h1>
        <p className="text-muted-foreground">
          Insights and statistics about your crop sales.
        </p>
      </div>

      {/* KPI Cards */}
      <div className="grid gap-4 md:grid-cols-3">

        <Card>
          <CardHeader>
            <CardTitle>Total Listings</CardTitle>
            <CardDescription>Your active crop listings</CardDescription>
          </CardHeader>

          <CardContent>
            <p className="text-3xl font-bold">12</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Total Sales</CardTitle>
            <CardDescription>Overall crop sales</CardDescription>
          </CardHeader>

          <CardContent>
            <p className="text-3xl font-bold">₹1,32,000</p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Active Buyers</CardTitle>
            <CardDescription>Buyers purchasing your crops</CardDescription>
          </CardHeader>

          <CardContent>
            <p className="text-3xl font-bold">23</p>
          </CardContent>
        </Card>

      </div>

      {/* Charts Row */}
      <div className="grid gap-6 lg:grid-cols-2">

        {/* Monthly Sales Chart */}
        <Card>

          <CardHeader>
            <CardTitle>Monthly Sales</CardTitle>
            <CardDescription>
              Track your sales performance over months
            </CardDescription>
          </CardHeader>

          <CardContent>

            <ResponsiveContainer width="100%" height={300}>

              <LineChart data={monthlySales}>

                <CartesianGrid strokeDasharray="3 3" />

                <XAxis dataKey="month" />

                <YAxis />

                <Tooltip />

                <Line
                  type="monotone"
                  dataKey="sales"
                  stroke="#22c55e"
                  strokeWidth={3}
                />

              </LineChart>

            </ResponsiveContainer>

          </CardContent>

        </Card>

        {/* Crop Distribution */}
        <Card>

          <CardHeader>
            <CardTitle>Crop Distribution</CardTitle>
            <CardDescription>
              Which crops you sell the most
            </CardDescription>
          </CardHeader>

          <CardContent>

            <ResponsiveContainer width="100%" height={300}>

              <PieChart>

                <Pie
                  data={cropData}
                  dataKey="value"
                  nameKey="name"
                  cx="50%"
                  cy="50%"
                  outerRadius={100}
                  label
                >

                  {cropData.map((entry, index) => (
                    <Cell key={index} fill={COLORS[index % COLORS.length]} />
                  ))}

                </Pie>

                <Tooltip />

              </PieChart>

            </ResponsiveContainer>

          </CardContent>

        </Card>

      </div>

      {/* Revenue Chart */}
      <Card>

        <CardHeader>
          <CardTitle>Revenue by Crop</CardTitle>
          <CardDescription>
            Compare revenue generated by each crop
          </CardDescription>
        </CardHeader>

        <CardContent>

          <ResponsiveContainer width="100%" height={300}>

            <BarChart data={cropData}>

              <CartesianGrid strokeDasharray="3 3" />

              <XAxis dataKey="name" />

              <YAxis />

              <Tooltip />

              <Bar dataKey="value" fill="#22c55e" />

            </BarChart>

          </ResponsiveContainer>

        </CardContent>

      </Card>

    </div>
  )
}